// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJfgBW6FWkuwzQwrjPMAUoJdBV_O45EO4',
    appId: '1:905922407036:web:9ed785ee14cce34b1cf7f9',
    messagingSenderId: '905922407036',
    projectId: 'makiprint-c1f86',
    authDomain: 'makiprint-c1f86.firebaseapp.com',
    storageBucket: 'makiprint-c1f86.firebasestorage.app',
    measurementId: 'G-LMT818JDE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7jeUSTJYKs3m2BmziuE5p-xphkZvzVc',
    appId: '1:905922407036:android:e84688888b623e361cf7f9',
    messagingSenderId: '905922407036',
    projectId: 'makiprint-c1f86',
    storageBucket: 'makiprint-c1f86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7ZPY_je9bG8X3IkrfB-t7iYAZXXQnUw',
    appId: '1:905922407036:ios:396e5ed264c37fda1cf7f9',
    messagingSenderId: '905922407036',
    projectId: 'makiprint-c1f86',
    storageBucket: 'makiprint-c1f86.firebasestorage.app',
    iosBundleId: 'com.example.makiprintClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7ZPY_je9bG8X3IkrfB-t7iYAZXXQnUw',
    appId: '1:905922407036:ios:396e5ed264c37fda1cf7f9',
    messagingSenderId: '905922407036',
    projectId: 'makiprint-c1f86',
    storageBucket: 'makiprint-c1f86.firebasestorage.app',
    iosBundleId: 'com.example.makiprintClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJfgBW6FWkuwzQwrjPMAUoJdBV_O45EO4',
    appId: '1:905922407036:web:d1c79dec749704161cf7f9',
    messagingSenderId: '905922407036',
    projectId: 'makiprint-c1f86',
    authDomain: 'makiprint-c1f86.firebaseapp.com',
    storageBucket: 'makiprint-c1f86.firebasestorage.app',
    measurementId: 'G-PRQTN9B856',
  );
}
